name: "📝 Task"
description: "Create a new task for the Intermarché Wine & Cheese project"
title: "[TASK] "
labels:
  - task
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the fields below to describe the work to be done.
  - type: input
    id: title
    attributes:
      label: "Task Title"
      description: "As a…, I want…, so that…"
      placeholder: "e.g. As a user, I want to search by dish so that I can find pairings"
      required: true
  - type: dropdown
    id: owner
    attributes:
      label: "Owner"
      description: "Who is responsible for this task?"
      options:
        - "Abderrazaq"
        - "Quentin"
        - "Pierre"
        - "Evan"
        - "David"
        - "Manech"
      required: true
  - type: number
    id: estimate
    attributes:
      label: "Estimate (hours)"
      description: "Rough estimate of effort in hours"
      placeholder: "e.g. 8"
  - type: dropdown
    id: sprint
    attributes:
      label: "Sprint"
      options:
        - "S1"
        - "S2"
        - "S3"
        - "S4"
        - "S5"
      required: true
  - type: dropdown
    id: milestone
    attributes:
      label: "Milestone"
      options:
        - "Functional Spec"
        - "Technical Spec"
        - "Test Plan"
        - "MVP Bubble"
        - "Final Delivery"
        - "Final Presentation"
  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options:
        - "High"
        - "Medium"
        - "Low"
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Detailed description of what needs to be done"
      placeholder: "Enter task details here…"
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria"
      description: "Use markdown checklist format"
      placeholder: |
        - [ ] Criterion 1  
        - [ ] Criterion 2  
        - [ ] Criterion 3  
